src/main/java/com/powsybl/study/server/dto/NetworkInfos.java, src/main/java/com/powsybl/study/server/dto/StudyInfos.java, src/main/java/com/powsybl/study/server/dto/VoltageLevelAttributes.java
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
bug fix
"com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.powsybl.study.server.dto.NetworkInfos` (no Creators, like default construct, exist):"
no exception
=> add default constructor for jackson

.github/workflows/maven.yml, README.md, src/test/java/org/gridsuite/study/server/StudyTest.java
NO
Bug Fix
CI fails and documentation is out of date because casssandra-4-alpha3 is not longer downloadable
using cassandra-4-alpha4
no
=> upgrade to cassandra-4.0-alpha4, alpha3 is no longer available

src/main/resources/application.yml
To stream, we just have to use Flux<DataBuffer>, but this means longer connections on the backend services
=> increase webclient buffer size as we don't stream the response.

src/main/resources/application.yml
at startup:
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. Cluster state is offline.
Caused by: org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. Cluster state is offline.
at org.springframework.data.elasticsearch.client.reactive.SingleNodeHostProvider.lambda$lookupActiveHost$4(SingleNodeHostProvider.java:109) ~[spring-data-elasticsearch-4.1.9.jar:4.1.9]
at every healthcheck:
2021-10-01 08:13:41.037  WARN 1 --- [or-http-epoll-4] a.e.ElasticsearchReactiveHealthIndicator : Elasticsearch health check failed
org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. …
=> Disable reactive elasticsearch client which fails

src/main/java/org/gridsuite/study/server/elasticsearch/ESConfig.java, src/main/resources/application.yml
The timeout of the elasticsearch has 5 seconds as default value.
It's too limited to index a large network and if the indexing fails then the import also fails
`org.springframework.dao.DataAccessResourceFailureException: 5,000 milliseconds timeout on connection http-outgoing-2 [ACTIVE]; nested exception is java.lang.RuntimeException: 5,000 milliseconds timeout on connection http-outgoing-2`
The timeout is now configurable with 60 seconds as default value
=> Elasticsearch client timeout

src/main/java/org/gridsuite/study/server/networkmodificationtree/ModelNodeInfoRepositoryProxy.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java
Default model node created when a study is created should have a buildStatus equal to BUILT.
=> Fix default model node creation

src/main/java/org/gridsuite/study/server/NetworkService.java, src/main/java/org/gridsuite/study/server/StudyService.java
ix(NetworkService, StudyService): Add @Lazy annotation to avoid initialization when elasticsearch service isn't available at start.
Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>
=> Add @Lazy annotation to avoid initialization when elasticsearch service isn't available at start

src/main/java/org/gridsuite/study/server/StudyService.java
We get the following exceptions in the logs, the client reports a red box "study has a problem please recreate"
2022-07-04 08:32:22.260 ERROR 1 --- [ool-1-thread-21] org.gridsuite.study.server.StudyService  : org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.gridsuite.study.server.networkmodificationtree.entities.NodeEntity.study -> org.gridsuite.study.server.repository.StudyEntity; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : org.gridsuite.study.server.networkmodificationtree.entities.N …
=> Fix race conditions when creating studies (TransientPropertyValueException save before flushing)

src/main/resources/config/application.yaml
For example, we get the following
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "studyPK"
Detail: Key (id)=(07538685-7476-4dbd-98e1-52471ee88069) already exists.
because multiple study servers try to insert the study after the case is imported
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
=> Add group to study import success consummer, needed when multiple pods

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/main/java/org/gridsuite/study/server/service/dynamicsimulation/DynamicSimulationService.java, src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java, src/test/java/org/gridsuite/study/server/StudyControllerDynamicSimulationTest.java, src/test/java/org/gridsuite/study/server/service/StudyServiceDynamicSimulationTest.java, src/test/java/org/gridsuite/study/server/service/dynamicsimulation/DynamicSimulationServiceTest.java
Cause: in my opinion, the loop infinite is from the definition of type TimeSeries in recursive manner!
`TimeSeries<P extends AbstractPoint, T extends TimeSeries<P, T>>`
Solution: 
- Return with a parameterized type DoubleTimeSeries for timeseries and StringTimeSeries for timeline 
- Check type a service level, if KO throw an exception
=> Swagger API not accept generic type TimeSeries as return type

src/test/java/org/gridsuite/study/server/service/client/AbstractRestClientTest.java, src/test/java/org/gridsuite/study/server/service/client/dynamicmapping/DynamicMappingClientTest.java, src/test/java/org/gridsuite/study/server/service/client/dynamicsimulation/DynamicSimulationClientTest.java, src/test/java/org/gridsuite/study/server/service/client/timeseries/TimeSeriesClientTest.java
Problem occurs when running dynamic-simulation-server, dynamic-mapping-server by docker-compose at local
=> Dynamic simulation - use dynamic port for mock web server in unit tests

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/NetworkModificationNodeInfoRepositoryProxy.java, src/test/java/org/gridsuite/study/server/StudyControllerDynamicSimulationTest.java
In order to reset a field to null value in the table, must provide field's name in method updateNode
see AbstractNodeRepositoryProxy#updateNode(AbstractNode node, String... authorizedNullProperties)
=> Dynamic simulation - manage in case of failed run

pom.xml
Now included by https://github.com/powsybl/powsybl-ws-dependencies/pull/7
Signed-off-by: Florent MILLOT <millotflo@gmail.com>
=> Remove WireMock version

src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/ReportService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java, src/test/java/org/gridsuite/study/server/service/ReportServiceTest.java
This PR works only with branch _logs_optimization_ from _report-server_ (no PR at this time)
=> logs on demand

src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java
Rename `buildNetworkModification` to `buildNetworkModificationNode` because it builds a node and NetworkModification is something else.
Rename parameter `idHypo` to `modificationGroupUuid` for the same clarity reason.
=> Refactor NetworkModificationTreeTest method buildNetworkModification

src/main/java/org/gridsuite/study/server/service/SecurityAnalysisService.java
The security analysis params default values are overload when getting the params but not when security analysis computation is run.
We need to use the overloaded values for both scenarios if the security analysis params are absent.
=> Fix security analysis params overload

src/main/java/org/gridsuite/study/server/service/SupervisionService.java
All short-circuit results are removed in the "shortcircuit" database, but:
- When we call _delete_computation_results.py_ admin tool before this PR, only all-buses results are reset to null in the study database.
- Now one-bus results are set to null too.
=> fix: shortcircuit results deletion must reset to null both all-buses and one-bus results

src/test/java/org/gridsuite/study/server/config/DisableAmqp.java, src/test/java/org/gridsuite/study/server/config/DisableCloudStream.java, src/test/java/org/gridsuite/study/server/config/DisableJpa.java, src/test/java/org/gridsuite/study/server/config/ExcludeSpringBootTestComponents.java, src/test/java/org/gridsuite/study/server/utils/elasticsearch/DisableElasticsearch.java, src/test/resources/META-INF/spring.factories
Add `@DisableJPA` & `@DisableAmqp`, like exisitng `@DisableElasticsearch` for disabling part of Spring during `@SpringBootTest` tests.
When adding annotation on a test class with `@SpringBootTest`, we set some annotations for:
* `@MockBean` to replace beans/classes (like jpa repositories) need by for example services; or bean like amqp streambridge which isn't init/created
* `@TestPropertySource` to set spring property, use by filter (see below)
Spring-Boot will during its auto-configuration discover the filter via `spring.factories` file, and call it which permit us to exclude some parts from initialization.
=> Add annotations to disable SQL/JPA & AMQP

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/ConsumerService.java, src/main/java/org/gridsuite/study/server/service/SecurityAnalysisService.java, src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/main/java/org/gridsuite/study/server/service/client/dynamicsimulation/DynamicSimulationClient.java, src/main/java/org/gridsuite/study/server/service/client/dynamicsimulation/impl/DynamicSimulationClientImpl.java, src/main/java/org/gridsuite/study/server/service/dynamicsimulation/DynamicSimulationService.java, src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java, src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java, src/test/java/org/gridsuite/study/server/SensitivityAnalysisTest.java, src/test/java/org/gridsuite/study/server/ShortCircuitTest.java, src/test/java/org/gridsuite/study/server/StudyControllerDynamicSimulationTest.java, src/test/java/org/gridsuite/study/server/service/StudyServiceDynamicSimulationTest.java, src/test/java/org/gridsuite/study/server/service/client/dynamicsimulation/DynamicSimulationClientTest.java, src/test/java/org/gridsuite/study/server/service/dynamicsimulation/DynamicSimulationServiceTest.java
Adds userId as a parameter when running 
* security analysis
* dynamic simulation
* sensibility analysis
Also transmits the header "messages" to the front as an error message.
In itself this branch won't change anything noticeable to how the computation works because the error messages are empty anyway. 3 more branches will be needed in the computation microservices in order to handle the error message and user id. For now they "can" be handled but they are empty anyway.
=> handle user id and error message in various computation consumers

src/test/java/org/gridsuite/study/server/utils/elasticsearch/EmbeddedElasticsearch.java
* Add same environment variables for the embedded elastic search container as in docker-compose.
* Limit the memory (Xms/Xmx) to 128m because since ES 7.11.0, heap settings are based on node roles and total system memory [#65905](https://github.com/elastic/elasticsearch/pull/65905). Heap memory default values are computed as :
`50% of total system memory when greater than 1 gigabyte up to a maximum of 31 gigabytes`
cf. https://github.com/gridsuite/deployment/commit/42d43729424b87040a724df027f8bd8d9cb41b1f.
We cannot accept to allocate 16Go for an embedded ES.
=> Add environment variable for embedded ES container

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/client/timeseries/impl/TimeSeriesClientImpl.java, src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java, src/test/java/org/gridsuite/study/server/service/client/timeseries/TimeSeriesClientTest.java
**Correction in this PR:**
1. When timeseries uuid is empty, do not send request to time-series-server
**Related PRs:**
GridStudy-app : https://github.com/gridsuite/gridstudy-app/pull/1870 (with demo)
Dynamic-simulation-server : https://github.com/gridsuite/dynamic-simulation-server/pull/86
=> Dynamic Simulation - Exception when running simulation without curves

src/main/java/org/gridsuite/study/server/notification/NotificationService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Some error (like in the conversion-server) don't return any error message. But during the message handling in directory-server and gridexplore those notification need an error message in order to interpret those notification as errors and act accordingly.
A simple default "Unknown error" is aded for those cases.
NOTE : new error notifcation types could be added for a cleaner code, but it would mean too much change for now.
=> default error message for Study Creation Error

src/main/java/org/gridsuite/study/server/repository/networkmodificationtree/NodeRepository.java, src/main/java/org/gridsuite/study/server/service/NetworkModificationTreeService.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java
fix(): When restoring a subtree, do not send a `nodeCreated` notifica…tion for each nodes in the subtree but a single notification to `insertSubtree` and all its children.
fix(): RestoreNode now use the `InsertMode.CHILD` to add a new branch instead of trying to insert a node between the parent and already existing children. It causes unexpected behaviors.
=> Fix node and subtree restoration

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/main/java/org/gridsuite/study/server/service/SupervisionService.java, src/test/java/org/gridsuite/study/server/RootNetworkTest.java
When there are root networks in creation in the table **root_network_creation_request** (we need to investigate why there are some rows that remain here and never get deleted => crash of pod, error on import, etc), we try to invalidate node/delete index on these networks that don't exist yet which throw an error "ROOT_NETWORK_NOT_FOUND" as it does not exist.
In this PR, I propose to use only existing root network for supervision endpoints: to invalidate nodes and delete indexed equipments.
=> Fix supervision endpoints error with root networks in creation

src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/StudyControllerDynamicSimulationTest.java
DSA depends on DS, so need to invalidate DSA result when updating DS parameters or provider
=> [Dynamic Security Analysis] Invalidate DSA result when update DS parameters

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/notification/NotificationService.java, src/main/java/org/gridsuite/study/server/service/RootNetworkService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/rootnetworks/RootNetworkTest.java
rename notification headers accordingly
refactor(NotificationService): create a private method `sendStudyUpdateMessage` wich always set studyUuid and updateType headers making it mandatory. refactor(NotificationService): remove rootNetworkModified notification which is a rootNetworkUpdated notification with a root network uuid in header
=> Refactor RN notifications: rename root network notifications variables for uuid or list of uuids

pom.xml, src/main/java/org/gridsuite/study/server/RestTemplateConfig.java
All our services use the default version of HTTP client provided by spring-web. Here in study-server we introduced a new HTTP client provided by apache httpclient5. We have to double check with @ayolab if there was an important reason to do so. But to keep it harmonized between our services we prefer to remove it for now. 
We witnessed unwanted side-effect of this client due to a pool of HTTP request that was very limited (only 5 per host, under load this would make all requests take minutes waiting for this pool!) and hard to configure (no spring auto-configuration)
=> fix: remove httpclient5

src/main/java/org/gridsuite/study/server/controller/StudyController.java, src/test/java/org/gridsuite/study/server/StudyControllerDynamicSecurityAnalysisTest.java, src/test/java/org/gridsuite/study/server/StudyControllerDynamicSimulationTest.java
Related PR front : https://github.com/gridsuite/gridstudy-app/pull/3292
EDIT: This PR was originally done to fix various (sometimes 1s, sometimes 200ms) performance problems but empirically this change doesn't affect performance or only in the order of miliseconds
=> get status of DS and DSA, return string not enum like other statuses
