src/main/java/com/powsybl/study/server/StudyService.java, src/main/java/com/powsybl/study/server/dto/StudyInfos.java, src/main/java/com/powsybl/study/server/repository/Study.java, src/main/resources/study.cql, src/test/java/com/powsybl/study/server/StudyTest.java
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>
=> add caseFormat as a new study info

src/main/java/com/powsybl/study/server/StudyConstants.java, src/main/java/com/powsybl/study/server/StudyController.java, src/main/java/com/powsybl/study/server/StudyService.java, src/main/resources/application.yml, src/test/java/com/powsybl/study/server/StudyTest.java
Add two new method to forward requests to network-map-server
=> Add new methods

src/main/java/com/powsybl/study/server/StudyController.java, src/main/java/com/powsybl/study/server/StudyService.java, src/main/java/com/powsybl/study/server/dto/CaseInfos.java, src/test/java/com/powsybl/study/server/CaseInfosTest.java, src/test/java/com/powsybl/study/server/StudyTest.java
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>
=> add casInfos instead of Map<String,String>

src/main/java/com/powsybl/study/server/StudyController.java, src/main/java/com/powsybl/study/server/StudyService.java, src/test/java/com/powsybl/study/server/StudyTest.java
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>
=> Add useName param to get svg

src/main/java/com/powsybl/study/server/StudyController.java, src/main/java/com/powsybl/study/server/StudyService.java, src/test/java/com/powsybl/study/server/StudyTest.java
NO
Feature
svg-and-metadata not exposed in studyserver
svg-and-metadata exposed in studyserver
NO
=> Add svg-and-metadata

.github/workflows/maven.yml, README.md, pom.xml, src/main/java/org/gridsuite/study/server/CassandraConfig.java, src/main/java/org/gridsuite/study/server/CassandraConstants.java, src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyApi.java, src/main/java/org/gridsuite/study/server/StudyApplication.java, src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/StudySwaggerConfig.java, src/main/java/org/gridsuite/study/server/dto/CaseInfos.java, src/main/java/org/gridsuite/study/server/dto/NetworkInfos.java, src/main/java/org/gridsuite/study/server/dto/StudyInfos.java, src/main/java/org/gridsuite/study/server/dto/VoltageLevelAttributes.java, src/main/java/org/gridsuite/study/server/repository/Study.java, src/main/java/org/gridsuite/study/server/repository/StudyRepository.java, src/test/java/org/gridsuite/study/server/CaseInfosTest.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> Rename to GridSuite

src/main/java/org/gridsuite/study/server/StudyController.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>
=> remove unused endpoint

src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/dto/CaseInfos.java, src/main/java/org/gridsuite/study/server/repository/Study.java, src/main/resources/study.cql, src/test/java/org/gridsuite/study/server/CaseInfosTest.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
=> update rest api to reflect case-server changes

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
This is just a synchronization with new single line diagram server topological coloring new feature.
=> Support topological coloring of single line diagrams

src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/resources/application.yml
Signed-off-by: NOIR Nicolas ext <nicolas.noir@rte-france.com>
=> Addition of loadflow service call

pom.xml, src/test/java/org/gridsuite/study/test/EmbeddedCassandraFactoryConfig.java
No
Bug fix
timeouts in CI
hopefully no more timeouts in CI
NO
=> Cassandra tests: up the timeout to 15 minutes

src/main/java/org/gridsuite/study/server/StudyController.java
=> fix regression of 56c7d57c for /geo-data/lines

pom.xml
=> remove exlusion

pom.xml, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/resources/application.yml, src/test/java/org/gridsuite/study/server/StudyTest.java
=> websocket notification

src/main/java/org/gridsuite/study/server/StudyController.java
Signed-off-by: HOMER Etienne <etiennehomer@gmail.com>
=> Refractoring: use ResponseEntity<Mono> instead of Mono<ResponseEntity>

.github/workflows/maven.yml
=> fix image name

src/main/java/org/gridsuite/study/server/CassandraConfig.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/dto/LoadFlowStatus.java, src/main/java/org/gridsuite/study/server/dto/StudyInfos.java, src/main/java/org/gridsuite/study/server/repository/AllStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/AllStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/LoadFlowResultEntity.java, src/main/java/org/gridsuite/study/server/repository/PrivateStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/PrivateStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/PublicAndPrivateStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/PublicAndPrivateStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/PublicStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/PublicStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/StudyEntity.java, src/main/java/org/gridsuite/study/server/repository/StudyRepository.java, src/test/java/org/gridsuite/study/server/StudyTest.java
- To avoid 3 repos boilerplate in study service, creation of a facade repository for studies that hide denormalisation of data
- Study entities (so database objects) are not anymore exposed to controller and serialized to REST API. It is a bad practice to expose DB entities to REST API.
=> Study repository factoring

pom.xml, src/main/java/org/gridsuite/study/server/CassandraConfig.java, src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyApplication.java, src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/StudySwaggerConfig.java, src/main/java/org/gridsuite/study/server/WebFluxConfig.java, src/main/java/org/gridsuite/study/server/repository/PrivateStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/PrivateStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/PublicAndPrivateStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/PublicAndPrivateStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/PublicStudyEntity.java, src/main/java/org/gridsuite/study/server/repository/PublicStudyRepository.java, src/main/java/org/gridsuite/study/server/repository/StudyEntity.java, src/main/java/org/gridsuite/study/server/repository/StudyRepository.java, src/main/resources/application.yml, src/main/resources/study.cql, src/test/java/org/gridsuite/study/server/StudyTest.java
=> Security analysis integration

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Prevent topology modification during a loadflow.
Code 403 is returned in this case
=> Prevent topology modification during a computation (LF&AS)

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/WebFluxConfig.java, src/main/java/org/gridsuite/study/server/repository/StudyCreationRequestRepository.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> Delete study being created

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
This PR must be merged together with : 
https://github.com/powsybl/powsybl-single-line-diagram-server/pull/38
=> Add diagram for substations

pom.xml, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/repository/LoadFlowParametersEntity.java, src/main/resources/study.cql, src/test/java/org/gridsuite/study/server/StudyTest.java
=> Migrate to GridSuite dependencies v3

src/main/java/org/gridsuite/study/server/StudyService.java
=> Remove spurious synchronize. it slipped in.

src/test/java/org/gridsuite/study/server/StudyTest.java
=> Fix compilation error in studyTest

src/main/java/org/gridsuite/study/server/StudyService.java
=> Fix compilation errors with jdk 11.0.5

src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/dto/CreatedStudyBasicInfos.java, src/main/java/org/gridsuite/study/server/dto/StudyInfos.java, src/test/java/org/gridsuite/study/server/StudyTest.java, src/test/java/org/gridsuite/study/server/utils/MatcherCreatedStudyBasicInfos.java, src/test/java/org/gridsuite/study/server/utils/MatcherStudyInfos.java
=> move description to CreatedStudyBasicInfos

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> rename endpoint should return CreatedStudyBasicInfos

src/test/java/org/gridsuite/study/server/StudyTest.java, src/test/java/org/gridsuite/study/server/utils/MatcherCreatedStudyBasicInfos.java
=> change args order in createMatcherCreatedStudyBasicInfos

src/main/java/org/gridsuite/study/server/StudyService.java
=> Bug fix for modification group deletion

README.md
This prevents it from failing when the file doesn't exist..
=> add "-f" to readme example to regenerate the schema

src/main/java/org/gridsuite/study/server/repository/LoadFlowResultEntity.java, src/main/resources/study.sql
Signed-off-by: jacqbors <jacques.borsenberger@rte-france.com>
=> add index on join column

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Fix notifications for private studies to send them only to owner and not to all users
=>  Fix notifications for private studies to send them only to owner

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Addition of new methods for line lockout and trip
=> Addition of new methods for line lockout and trip

pom.xml, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/repository/ComponentResultEmbeddable.java, src/main/resources/study.sql, src/test/java/org/gridsuite/study/server/StudyTest.java, src/test/java/org/gridsuite/study/server/repository/RepositoriesTest.java
=> Migrate to PowSyBl Core 4.2.0

pom.xml, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/resources/application.yml
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
=> springboot 2.4.7

pom.xml
=> Use powsybl-parent v5 for non root base image

src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/resources/application.yml, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: jacqbors <jacques.borsenberger@rte-france.com>
=> integration with report server

src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> handle 'insert in directory server fails'

src/main/java/org/gridsuite/study/server/StudyService.java
=> change method for directory insertion

src/test/java/org/gridsuite/study/server/StudyTest.java
=> Fix unit test compilation

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/dto/RenameStudyAttributes.java
=> fix rename

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/dto/modification/ModificationType.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> add 2 windings transformer creation

src/main/java/org/gridsuite/study/server/dto/EquipmentInfos.java
Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>
=> Fix elasticsearch prefix env variable name

src/main/java/org/gridsuite/study/server/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/AbstractNodeRepositoryProxy.java, src/main/java/org/gridsuite/study/server/utils/PropertyUtils.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java
Signed-off-by: jacques borsenberger <jacques.borsenberger@rte-france.com>
=> keep data on node update

src/main/java/org/gridsuite/study/server/NetworkModificationService.java, src/main/java/org/gridsuite/study/server/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/repository/StudyCreationRequestRepository.java, src/main/java/org/gridsuite/study/server/repository/StudyRepository.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java, src/test/java/org/gridsuite/study/server/StudyTest.java, src/test/java/org/gridsuite/study/server/repository/RepositoriesTest.java
=> Normalize the rest api and remove access controls with the user

src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> reflect map-server api changes

src/main/java/org/gridsuite/study/server/StudyController.java
Signed-off-by: Etienne Homer <etiennehomer@gmail.com>
=> code 204 for nodes without AS uuid

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/EquipmentInfosServiceTests.java, src/test/java/org/gridsuite/study/server/StudyServiceSearchTests.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> copy load infos from existing one

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> get mapdata for equipments

src/main/java/org/gridsuite/study/server/NetworkModificationService.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: jacques borsenberger <jacques.borsenberger@rte-france.com>
=> reorder modifications

src/main/java/org/gridsuite/study/server/StudyService.java
=> Fix : need to save "running" LF status in database before running LF

src/main/java/org/gridsuite/study/server/StudyService.java, src/main/java/org/gridsuite/study/server/repository/LoadFlowParametersEntity.java, src/main/resources/db/changelog/changesets/changelog_2022-06-01T12:46:54Z.xml, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/org/gridsuite/study/server/repository/RepositoriesTest.java
Adds new LoadFlow parameters in Settings.
=> Adds missing loadflow parameters

src/main/java/org/gridsuite/study/server/NetworkModificationService.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> Fix : randomly failing unit tests

src/main/java/org/gridsuite/study/server/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: Etienne Homer <etiennehomer@gmail.com>
=> block modification when one node building

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyService.java
Signed-off-by: Etienne Homer <etiennehomer@gmail.com>
=> improve error message on modification blocked

src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Fix network modifications notifications types
Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>
Co-authored-by: bendaamerahm <ahmed.bendaamer@rte-france.com>
=> Fix network modifications notifications types

src/main/resources/db/changelog/changesets/changelog_2022-06-27T12:34:33Z.xml, src/main/resources/db/changelog/db.changelog-master.yaml
=> Fix distributed_active_power migration

src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
add notification for hypothesis when : 
- change switch state
- apply groovy script
- change line status
=> add notification for hypothesis

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/main/resources/config/application.yaml, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>
=> New method to consume node build failed messages and send notifications to frontend

src/main/java/org/gridsuite/study/server/StudyService.java, src/main/resources/config/application.yaml, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>
=> New consumer to get failed security analysis messages and send them to frontend

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> add getVoltageLevels

src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> fix: remove possible old reports "before" building node

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> send notification on study metadata update

src/main/java/org/gridsuite/study/server/dto/TombstonedEquipmentInfos.java
=> Fix the elasticsearch index prefix property for TombstonedEquipmentInfos

src/main/java/org/gridsuite/study/server/NetworkModificationService.java, src/main/java/org/gridsuite/study/server/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/dto/TombstonedEquipmentInfos.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/AbstractNodeRepositoryProxy.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/NetworkModificationNodeInfoRepositoryProxy.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/dto/AbstractNode.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/dto/NetworkModificationNode.java, src/main/java/org/gridsuite/study/server/networkmodificationtree/entities/NetworkModificationNodeInfoEntity.java, src/main/resources/db/changelog/changesets/changelog_2022-07-16T11:57:44Z.xml, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java, src/test/java/org/gridsuite/study/server/StudyTest.java
=> Reset variant id and report when a modification node become invalid

src/main/java/org/gridsuite/study/server/networkmodificationtree/AbstractNodeRepositoryProxy.java
=> Fix report uuid root node (never changes)

src/main/java/org/gridsuite/study/server/StudyService.java
=> Fix encoding slash for voltage level ids

src/main/resources/config/application.yaml
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
=> Add missing groups and standardize concurrency parameter

src/main/java/org/gridsuite/study/server/service/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/service/NotificationService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/StudyTest.java
Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>
=> When moving a node, build status are now correctly changed

src/test/java/org/gridsuite/study/server/NetworkModificationTest.java
=> Purge verified test requests with wiremock

src/main/java/org/gridsuite/study/server/elasticsearch/EquipmentInfosRepository.java, src/main/java/org/gridsuite/study/server/elasticsearch/EquipmentInfosService.java, src/main/java/org/gridsuite/study/server/elasticsearch/StudyInfosRepository.java, src/main/java/org/gridsuite/study/server/elasticsearch/StudyInfosService.java, src/main/java/org/gridsuite/study/server/elasticsearch/TombstonedEquipmentInfosRepository.java
=> Fix elastic search lazy starting for tests

src/main/java/org/gridsuite/study/server/networkmodificationtree/NetworkModificationNodeInfoRepositoryProxy.java, src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java, src/test/java/org/gridsuite/study/server/SensitivityAnalysisTest.java, src/test/java/org/gridsuite/study/server/ShortCircuitTest.java
Following to the PR: https://github.com/gridsuite/study-server/pull/344
=> Allow set null for resultUuid of 3 calculations: ShortCircuitAnalysis, SecurityAnalysis, SensitivityAnalysis

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/NetworkMapService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/NetworkMapTest.java, src/test/java/org/gridsuite/study/server/SingleLineDiagramTest.java
Add two new endpoints to get the nominal voltages and to get a line / 2WT / 3WT from an equipment ID.
=> Add two new endpoints to switch some logic from front end to back end

src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java, src/main/java/org/gridsuite/study/server/StudyException.java, src/main/java/org/gridsuite/study/server/dto/LoadFlowStatus.java, src/main/java/org/gridsuite/study/server/service/LoadflowService.java, src/test/java/org/gridsuite/study/server/LoadflowTest.java
To be merged together with PR : https://github.com/gridsuite/gridstudy-app/pull/1404
=> Fix unable to relaunch loadflow on error

lombok.config, pom.xml, src/test/java/org/gridsuite/study/server/EquipmentInfosServiceTests.java, src/test/java/org/gridsuite/study/server/Impacts/ElementImpactTest.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java, src/test/java/org/gridsuite/study/server/StudyInfosServiceTests.java, src/test/java/org/gridsuite/study/server/StudyServiceSearchTests.java
Use new lombok shared configuration (_see powsybl/powsybl-parent#44_)
Also fix wrong scope use for lombok dependency.
=> Update lombok config

src/main/resources/db/changelog/changesets/changelog_20230807T081915Z.xml, src/main/resources/db/changelog/db.changelog-master.yaml
Here are the missing indexes added : 
- study
- **study_load_flow_parameters_entity_id_index** _linked to a foreign key to load_flow_parameters_
- **short_circuit_parameters_entity_id** _linked to a foreign key to short_circuit_parameters_
- **study_dynamic_simulation_parameters_entity_id_index** _linked to a foreign key to dynamic_simulation_parameters_
- **study_security_analysis_parameters_entity_id_index** _linked to a foreign key to security_analysis_parameters_
- **study_voltage_init_parameters_entity_id_index** _linked to a foreign key to voltage_init_parameters_
- load_flow_specific_parameters
- **load_flow_parameters_id_index** _linked to a foreign key to load_flow_parameters_
- voltage_init_parameters_entity_constantqgenerators
- …
=> Add missing database indexes

src/main/java/org/gridsuite/study/server/StudyConstants.java, src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/NetworkModificationService.java, src/main/java/org/gridsuite/study/server/service/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java, src/test/java/org/gridsuite/study/server/VoltageInitTest.java, src/test/java/org/gridsuite/study/server/utils/WireMockUtils.java
DELETE /network-modifications (onlyStashed=false) -> delete all modifications (also stashed modification)
DELETE /network-modifications?onlyStashed=true -> delete all stashed modifications
GET /network-modifications (onlyStashed=false) -> get all modifications (also stashed modifications)
GET /network-modifications?onlyStashed=true -> get all stashed modifications
PUT /network-modifications?stashed=true -> stash modification
PUT /network-modifications?stashed=false -> restore modification
=> Improve stash api

src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/VoltageInitTest.java
value change for ModificationsGroupUuid when applying VoltageInitModifications for example
=> Add a notification when voltage init result changes 

src/main/java/org/gridsuite/study/server/repository/StudyEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/AbstractSensitivityFactorEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityAnalysisParametersEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityFactorForInjectionEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityFactorForNodeEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityFactorWithDistribTypeEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityFactorWithSensiTypeForHvdcEntity.java, src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityFactorWithSensiTypeForPstEntity.java
=> Mark obsolete entities sensi parameters as it

src/main/java/org/gridsuite/study/server/repository/LoadFlowParametersEntity.java, src/main/java/org/gridsuite/study/server/repository/LoadFlowSpecificParameterEntity.java, src/main/java/org/gridsuite/study/server/repository/StudyEntity.java
=> Mark obsolete entities loadflow parameters as it

src/main/java/org/gridsuite/study/server/repository/SecurityAnalysisParametersEntity.java, src/main/java/org/gridsuite/study/server/repository/StudyEntity.java
=> Mark obsolete entities security parameters as it

src/main/java/org/gridsuite/study/server/service/LoadFlowService.java, src/main/java/org/gridsuite/study/server/service/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/main/java/org/gridsuite/study/server/service/SupervisionService.java, src/main/java/org/gridsuite/study/server/service/VoltageInitService.java, src/main/java/org/gridsuite/study/server/service/shortcircuit/ShortCircuitService.java
The front-end has changed the "reportType" REST param from LOADFLOW to LOAD_FLOW. So we have to change it in ReportType enum.
For clarity, this PR also uses in ReportType the same enum values than in ComputationType.
=> Fix error when we try to display the loadflow report

src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/LoadFlowTest.java
This is for consistency with how it works from system default values
=> bugfix, don't reset provider for loadflow param reset from profile

src/main/java/org/gridsuite/study/server/service/LoadFlowService.java, src/main/java/org/gridsuite/study/server/service/SecurityAnalysisService.java, src/main/java/org/gridsuite/study/server/service/shortcircuit/ShortCircuitService.java
Missing `@Override` when refactoring code in #544.
=> Missing `@Override` from big refactor

src/main/java/org/gridsuite/study/server/service/StudyService.java
Remove unwanted constraint introduced by accident in #569
=> Fix unwanted constraint

src/main/java/org/gridsuite/study/server/StudyController.java, src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java, src/test/java/org/gridsuite/study/server/SensitivityAnalysisTest.java
nodeUuid is missing for the endpoint to get factors count for sensitivity computations
linked to https://github.com/gridsuite/gridstudy-app/pull/2164 and https://github.com/gridsuite/sensitivity-analysis-server/pull/89
=> add nodeUuid for sentivity factor count

pom.xml, src/main/java/org/gridsuite/study/server/service/ReportService.java, src/test/java/org/gridsuite/study/server/StudyTest.java, src/test/java/org/gridsuite/study/server/service/ReportServiceTest.java, src/test/java/org/gridsuite/study/server/utils/TestUtils.java
Update to gridsuite/dependencies#70
=> Upgrade to powsybl dependencies 2024.2.0

src/main/java/org/gridsuite/study/server/service/RootNetworkService.java, src/main/resources/config/application.yaml
Stopgap until we put it in the profile or the study configuration
=> Make root networks limits configurable in application.yml

src/main/java/org/gridsuite/study/server/service/NetworkModificationTreeService.java, src/main/java/org/gridsuite/study/server/service/StudyService.java, src/test/java/org/gridsuite/study/server/NetworkModificationTreeTest.java
> Create a security node
> Creation Rules
Construction Node
A construction node can be created anywhere from another construction node.
A construction node cannot be created from a security node.
Security Node
A security node can be created anywhere from another security node.
A security node can only be created as a new branch (InsertMode = CHILD) from a root node or a construction node.
=> create security node and adjust network modification node creation rules
